services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mynewpass
    ports:
      - "5434:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=billing_db
      - DB_USER=postgres
      - DB_PASS=rps_password
      - DB_HOST=db
    depends_on:
      - db
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run --token docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiOWYwZGE1YmRjODhkMGUwZDg0ZGM1ZThiMDg4MGMwNTIiLCJ0IjoiYzkwM2RlMmItNTc0Mi00OGU5LThhZjgtZDQ0Mjc5OGFhZDgwIiwicyI6IlpHRmxaV1F5TlRNdFpESmxOaTAwT0RVMUxUaGxZakF0WW1Rd01XSmxaamc0TnpWaiJ9
    depends_on:
      - backend

volumes:
  postgres_data: